config/routes.rb
Rails.application.routes.draw do
  root "employees#index"
  resources :vacation_ranges
  resources :employees
  get 'show/vacation_ranges/eligibles', to: 'vacation_ranges#show_vacation_eligibles', as: 'show_vacation_eligibles'
  get 'list/vacation_ranges/:employee_id', to: 'vacation_ranges#show_employee_ranges', as: 'show_employee_ranges'
  
 
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <%= link_to "Vacation Manager", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Adicionar
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
          
            <li><%= link_to "Colaborador", new_employee_path, class: "dropdown-item" %></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Período de férias", show_vacation_eligibles_path, class: "dropdown-item" %></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Férias cadastradas", vacation_ranges_path, class: "nav-link" %>
        </li>
      </ul>
    </div>
  </div>
</nav>